name: Generate Community Leaderboard

on:
  schedule:
    - cron: '35 9 * * *'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        DISCORD_WEBHOOK: ${{ secrets.OSS_DISCORD_WEBHOOK }}
      run: docker compose run --env DISCORD_WEBHOOK=$DISCORD_WEBHOOK --entrypoint "sh -c 'python3 oss_leaderboard.py'" lilypad_assistant