name: Get all community open issues

on:
  schedule:
    - cron: '0 16 * * 1,5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image and get all community open issues
      env:
        OSS_DISCORD_WEBHOOK: ${{ secrets.OSS_DISCORD_WEBHOOK }}
      run: docker compose run --env OSS_DISCORD_WEBHOOK=$OSS_DISCORD_WEBHOOK --entrypoint "sh -c 'python3 oss_issues.py'" lilypad_assistant