name: Support Reminder

on:
  schedule:
    # Runs every 4 days at 16:30 (4:30 PM UTC), starting 1 day after Ambassador Reminder
    - cron: "30 16 2-31/4 * *"
  workflow_dispatch:

jobs:
  run-support-reminder:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and run the support reminder bot
        env:
          SUPPORT_REMINDER_DISCORD_WEBHOOK: ${{ secrets.SUPPORT_REMINDER_DISCORD_WEBHOOK }}
        run: |
          docker compose run --env SUPPORT_REMINDER_DISCORD_WEBHOOK=$SUPPORT_REMINDER_DISCORD_WEBHOOK --entrypoint "sh -c 'python3 support_reminder.py'" lilypad_assistant
